[package]
name = "rnote-compression-benchmarking"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.*" }
plotters = { version = "0.3" }
itertools = { version = "0.13" }

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
debug = false
